### ISSUE TITLE
Private conversation chosen when selecting channel

### ISSUE THREAD

**Issue by parkerlreed** [sm00th/bitlbee-discord#176]
https://cdn.discordapp.com/attachments/486714034494767115/499784411001389066/unknown.png

This isn't the channel I joined. This is a multi user PM. What's going on here?

**Comment by dgw** [comment]
I don't think there's enough information here to answer the question. The channel topic says "BitlBee groupchat", whereas even my Discord channels with no topic set show their topics in BitlBee as "ServerName/channelname".

My best guess is you used the wrong ID in a join command, maybe from an old `chat list discord` output, and got joined to a multi-user PM instead of a channel that way. But I have no idea how close I am to the truth without being able to see your `&bitlbee` chat log leading up to joining this channel (which I realize might contain password/token data that would need to be redacted).

**Comment by parkerlreed** [comment]
I realize what I did.

````
chat add discord !1 #mydiscordchannel
````

I didn't realize !1 was the index number. I was using the channel name as mydiscordchanel there. !1 just so happens to be that group chat. Thanks.
