### ISSUE TITLE
Mentions are shown as numerical identifiers

### ISSUE THREAD

**Issue by madx** [sm00th/bitlbee-discord#2]
Hi

First and foremost, thank you very much for this project, it helped me regroup all my chats in my IRC client :-)

I have an issue though with mentions. When someone mentions somebody, it shows up as `<@105630595446521857>` instead of `@RealName`.

**Comment by madx** [comment]
After poking a bit with the API, it seems that what has to be done is replace these chunks using a request to `/users/<id>` to replace with the username.

**Comment by sm00th** [comment]
Yes, I am aware of this issue, it is also a two-way issue, i.e. when you mention someone's nick they won't get properly highlighted in discord because their id needs to be added to "mentions" array within the message structure.
I'll get on fixing this after I merge [ws branch](https://github.com/sm00th/bitlbee-discord/tree/ws) to master.

**Comment by madx** [comment]
Great news! Keep up the good work ;)

**Comment by kud** [comment]
:+1: 

I didn't know this pluging, it makes me want to use it. :)

**Comment by sm00th** [comment]
Fixed in 6bb5a8b

**Comment by madx** [comment]
Great :+1: Thanks a lot!

**Comment by kud** [comment]
Thanks :)
