### ISSUE TITLE
Group PMs dont show

### ISSUE THREAD

**Issue by tecknojock** [sm00th/bitlbee-discord#54]
PMs work fine, and servers chats work fine, but if you start a group PM then that does not show up in bitlbee, and one is forced to use discord for that.

**Comment by sm00th** [comment]
Looked into it a bit. At least at first glance the way this is implemented/presented in api is quite strange. They look mostly like normal pm's but are listed neither in "channels" (which is guild channels and I wouldn't expect them to be there), nor in "private channels". The only place where group pm id is mentioned in discord's init message is "read_status" structure which is used to keep track of seen messages.

These channels also don't have a name, so we'll have to generate, but I currently don't see how this can work with listchan branch.

Overall I think I'll have to postpone this till discord straightens things out a bit with this (assuming they have plans to do so).

**Comment by sm00th** [comment]
Turns out v6 of API does list those in "private_channels", so that makes it much easier, I'll just need to figure out a naming scheme for those and then they can be implemented as normal channels in bitlbee, though that means that with `listchan` branch (which will get merged to master soon I hope) a user would have to add/join them manually to receive messages from those, unlike with normal PMs.

**Comment by zertap** [comment]
Any eta on implementing this? would be neat.
